# Generated by Django 5.0.6 on 2024-06-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=16, verbose_name="用户名")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="DepartMent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=16, verbose_name="标题")),
            ],
        ),
        migrations.CreateModel(
            name="AssetSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名称")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(1, "办公类"), (2, "3C类"), (3, "房产类")],
                        verbose_name="资产类型",
                    ),
                ),
                (
                    "depart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.department",
                        verbose_name="所属部门",
                    ),
                ),
            ],
        ),
    ]
