# Generated by Django 5.0.6 on 2024-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="mobile",
            field=models.IntegerField(verbose_name="手机号"),
        ),
    ]
