# Generated by Django 5.0.6 on 2024-07-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_alter_staff_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_depart",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
                verbose_name="所属部门",
            ),
            preserve_default=False,
        ),
    ]
