# Generated by Django 5.0.6 on 2024-07-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_staff_staff_depart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="staff_depart",
            new_name="depart",
        ),
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=64, verbose_name="邮箱"),
        ),
        migrations.AlterField(
            model_name="staff",
            name="mobile",
            field=models.CharField(max_length=11, verbose_name="手机号"),
        ),
    ]
